/**
 * Service page copy.
 *
 * This lives next to `casos-de-exito.ts` rather than in `src/lib/constants.ts`
 * because it is content, not configuration, and it is the file that grows every
 * time a page is added. `constants.ts` re-exports it, so the existing import
 * sites keep working unchanged.
 *
 * Copy in TypeScript rather than MDX on purpose: a service page is a fixed
 * structure filled with data, so the compiler guarantees no page ships without
 * its FAQ or its price, and the JSON-LD and `llms.txt` are generated by walking
 * the same array instead of re-stating it.
 */

import type { FaqItem } from "@/types/content";

export type { FaqItem };

/** One alternating text/image block on a service detail page. */
export type ServiceSection = {
  title: string;
  body: string;
  image: string;
  imageAlt: string;
};

/** One numbered step of the working method. */
export type ProcessStep = {
  title: string;
  detail: string;
  /** What the client actually receives at the end of this step. */
  deliverable: string;
  timing: string;
};

/**
 * A starting price. `per: "mes"` is a retainer and maps to a schema.org Offer
 * with a UnitPriceSpecification; `per: null` is a one-off project price.
 *
 * TODO(lucas): confirmar los importes. Son suelos deliberadamente competitivos,
 * fijados en la mitad baja de la banda de mercado española de 2026 para que el
 * "desde" capture la búsqueda de precio; el importe real se cierra en la
 * llamada. Cambiarlos aquí los cambia a la vez en la página, en el schema
 * Offer, en /precios y en llms.txt.
 *
 * Si se sube alguno, revisa también el alcance declarado en `includes` y las
 * bandas de mercado citadas en las FAQ y en content/blog/cuanto-cuesta-
 * gestion-redes-sociales.mdx: el precio y el alcance tienen que ser creíbles
 * juntos.
 */
export type ServicePricing = {
  from: number;
  per: "mes" | null;
  /** Rendered label, e.g. "desde 490 € al mes". */
  label: string;
  includes: string[];
  excludes: string[];
  note: string;
};

export type Service = {
  slug: string;
  title: string;
  /** Short display name used in nav-style listings and cross-sell blocks. */
  shortTitle: string;
  /**
   * The on-page H1. Carries the city, which `title` does not: `title` is reused
   * in nav and card contexts where "en Barcelona" would be noise, but the H1 is
   * the strongest on-page signal after the <title> and has to say where.
   */
  h1: string;
  shortDescription: string;
  description: string;
  /** Lede shown under the H1 on the service detail page. */
  intro: string;
  /** SEO <title> for the detail page. */
  metaTitle: string;
  metaDescription: string;
  /**
   * 40-60 words answering the page's question completely, with no context from
   * the rest of the page. This is the block generative engines quote.
   */
  quickAnswer: string;
  /** Concrete deliverables. Nouns, not adjectives. */
  includes: string[];
  process: ProcessStep[];
  pricing: ServicePricing;
  /** Slugs from `content/casos-de-exito.ts` used as proof on this page. */
  proof: string[];
  /** Honest disqualification. Converts better than claiming to fit everyone. */
  notFor: string[];
  faq: FaqItem[];
  sections: ServiceSection[];
};

export const SERVICES: Service[] = [
  {
    slug: "gestion-redes-sociales",
    title: "Gestión de redes sociales",
    shortTitle: "Redes sociales",
    h1: "Gestión de redes sociales en Barcelona",
    shortDescription:
      "Gestiono tu cuenta entera: estrategia, guion, publicación y análisis. Con resultados a 30 días.",
    description:
      "Gestión completa de redes sociales para marcas: diagnóstico del perfil, línea editorial, guionaje, plan de grabación, publicación y análisis mensual de resultados para escalar lo que funciona y descartar lo que no.",
    intro:
      "Publicar más no arregla una cuenta estancada. Camping Collvert subió un 250 % sus visualizaciones en un mes sin publicar el doble: publicando otra cosa.",
    metaTitle: "Gestión de redes sociales en Barcelona",
    metaDescription:
      "Gestión de redes sociales en Barcelona desde 490 € al mes: estrategia, guion, publicación y análisis. +250 % de visualizaciones en un mes para Camping Collvert.",
    quickAnswer:
      "La gestión de redes sociales en Barcelona cuesta desde 490 € al mes e incluye diagnóstico del perfil, línea editorial, guion, edición, publicación y un informe mensual que termina en una decisión. La llevo yo personalmente, no un equipo rotativo. Las cuentas que gestiono subieron entre un 62 % y un 500 % de visualizaciones en su primer mes.",
    includes: [
      "Diagnóstico del perfil: formatos, retención, ganchos y audiencia real frente a la que crees tener",
      "Línea editorial escrita, con pilares de contenido y objetivos medibles por plataforma",
      "Guion de cada pieza y plan de grabación, para que el material se produzca sin bloquearte",
      "Edición y montaje de vídeo vertical para Reels, TikTok y Shorts",
      "Calendario y publicación en Instagram, Facebook, TikTok y YouTube",
      "Copy de cada publicación, con los primeros segundos escritos aparte porque son los que deciden",
      "Informe mensual que termina en una decisión: qué se escala, qué se retira y por qué",
      "Una llamada al mes para revisar el informe y ajustar el trimestre",
    ],
    process: [
      {
        title: "Diagnóstico",
        detail:
          "Reviso qué formatos has probado, en qué segundo se cae la retención, qué ganchos aguantan y a qué audiencia estás atrayendo de verdad. Salgo de aquí con una hipótesis concreta de por qué la cuenta no se mueve, no con una impresión general.",
        deliverable: "Documento de diagnóstico y línea editorial",
        timing: "Semana 1",
      },
      {
        title: "Validación del formato",
        detail:
          "Antes de tocar la frecuencia pruebo dos o tres formatos contra la audiencia real y espero a tener datos. Subir el ritmo con el formato equivocado solo multiplica el mismo error, y es el error que veo en casi todas las cuentas estancadas.",
        deliverable: "Formato ganador identificado con datos",
        timing: "Semanas 2-4",
      },
      {
        title: "Producción en serie",
        detail:
          "Con el formato validado la producción se vuelve repetible: guion con la misma estructura, grabación por bloques, edición con las mismas reglas. Es lo que permite sostener el ritmo sin que la calidad dependa de la inspiración de esa semana.",
        deliverable: "Calendario publicado y en marcha",
        timing: "Mes 2 en adelante",
      },
      {
        title: "Análisis y escalado",
        detail:
          "Cada mes el informe termina en una decisión, no en una gráfica. Se escala el formato que rinde y se retira el que no aporta. Camping Victòria multiplicó por seis sus visualizaciones justo aquí: duplicando la frecuencia solo después de saber qué duplicar.",
        deliverable: "Informe mensual con decisiones tomadas",
        timing: "Mensual",
      },
    ],
    pricing: {
      from: 490,
      per: "mes",
      label: "desde 490 € al mes",
      includes: [
        "Una plataforma principal y su réplica secundaria, por ejemplo Instagram y Facebook",
        "De 6 a 8 piezas al mes en el plan de entrada, ampliable según volumen",
        "Guion, edición, publicación e informe",
      ],
      excludes: [
        "La inversión publicitaria, si decidimos usarla",
        "Desplazamientos de grabación fuera del área de Barcelona",
        "Producción con equipo externo: actores, drones o localizaciones",
      ],
      note: "Sin permanencia. El primer mes es el que enseña si esto funciona, y prefiero que puedas irte después de verlo.",
    },
    proof: ["camping-collvert", "camping-puzol", "camping-victoria"],
    notFor: [
      "Quien busca a alguien que solo publique lo que le pase ya montado. Eso es un ejecutor de calendario, cuesta bastante menos y no lo hago yo.",
      "Quien necesita respuesta a comentarios y mensajes en menos de una hora durante todo el día. Eso es atención al cliente y requiere un equipo por turnos.",
      "Quien espera resultados sin aparecer nunca en cámara ni ceder material propio. Sin materia prima real no hay contenido que funcione.",
      "Quien quiere resultados garantizados por contrato. Nadie que entienda estas plataformas te va a firmar eso.",
    ],
    faq: [
      {
        question: "¿Cuánto cuesta la gestión de redes sociales en Barcelona?",
        answer:
          "Mi servicio empieza en 490 € al mes e incluye estrategia, guion, edición, publicación e informe mensual. En el mercado español un community manager freelance se mueve entre 300 y 1.200 € al mes, y una agencia entre 500 y 3.000 €. Empiezo en la mitad baja de esa banda porque trabajo solo y no tengo una estructura de agencia que sostener: lo que pagas es producción y criterio, no una capa comercial.",
      },
      {
        question: "¿En cuánto tiempo se ven resultados?",
        answer:
          "En visualizaciones y alcance, el primer mes. Camping Collvert subió un 250 % en su primer mes de gestión, Camping Puzol un 62 % y Reino Selva pasó de un crecimiento plano a 2,6 millones de visualizaciones. En seguidores y en clientes que llegan por esta vía, entre tres y seis meses: el alcance se mueve siempre antes que la conversión.",
      },
      {
        question: "¿Qué redes sociales gestionas?",
        answer:
          "Instagram, Facebook, TikTok y YouTube. Trabajo sobre todo vídeo vertical corto, que es el formato que mueve alcance hoy en casi cualquier sector. No gestiono X ni LinkedIn como canal principal, porque no es donde tengo resultados que enseñarte.",
      },
      {
        question: "¿Hay permanencia?",
        answer:
          "No. Trabajo mes a mes. El primer mes es el que demuestra si esto funciona en tu cuenta, y si después no quieres seguir no tienes que discutirlo con nadie.",
      },
      {
        question: "¿Tengo que salir yo en los vídeos?",
        answer:
          "No siempre, pero algo real de tu negocio sí. En los campings funciona el sitio: la parcela, el amanecer, la gente. En un negocio de servicios suele funcionar la persona. Lo que no funciona en ningún sector es el contenido de banco de imágenes.",
      },
      {
        question: "¿Trabajas con negocios fuera de Barcelona?",
        answer:
          "Sí. Tres de las cuentas que gestiono están en la costa catalana, fuera del área metropolitana, y trabajo también en remoto para el resto de España. Lo único que se acuerda aparte son los desplazamientos de grabación.",
      },
      {
        question: "¿Quién lleva mi cuenta exactamente?",
        answer:
          "Yo. No hay un comercial que te vende y otra persona que ejecuta. Es la pregunta que más cambia el resultado de una contratación y la que menos se hace, así que la respondo antes de que la hagas.",
      },
      {
        question: "¿Qué necesitas de mí para empezar?",
        answer:
          "Acceso a las cuentas, media hora para el diagnóstico inicial y disponibilidad para una sesión de grabación al mes. Nada más. El resto lo monto yo y te lo paso revisado antes de publicar.",
      },
    ],
    sections: [
      {
        title: "Primero el diagnóstico, después el calendario",
        body: "Antes de planificar una sola publicación reviso qué está pasando de verdad en tu perfil: qué formatos has probado, en qué segundo se cae la retención, qué ganchos aguantan, qué frecuencia sostienes y a qué audiencia estás atrayendo realmente frente a la que crees tener. De ahí sale una línea editorial concreta, con objetivos medibles por plataforma. La mayoría de cuentas estancadas no publican poco: publican lo que no toca.",
        image: "/images/placeholders/work-01.jpg",
        imageAlt:
          "Análisis de formatos y retención de una cuenta de Instagram gestionada por Lucas Álvarez",
      },
      {
        title: "Guion, grabación, publicación y análisis",
        body: "Me encargo del guion, del plan de grabación, de la edición, de la publicación y del seguimiento. Cada mes revisamos qué ha rendido y ajustamos: se escala el formato ganador y se retira el que no aporta. Es exactamente el proceso con el que Camping Puzol subió un 62 % sus visualizaciones en un mes y con el que Camping Victòria las multiplicó por seis al pasar de uno a dos posts semanales, una vez identificado el formato que le funcionaba.",
        image: "/images/placeholders/work-02.jpg",
        imageAlt:
          "Resultados mensuales de gestión de redes sociales para Camping Puzol y Camping Victòria",
      },
    ],
  },
  {
    slug: "estrategia-contenido-crecimiento-organico",
    title: "Estrategia de contenido y crecimiento orgánico",
    shortTitle: "Estrategia de contenido",
    h1: "Estrategia de contenido y crecimiento orgánico en Barcelona",
    shortDescription:
      "Un sistema de contenido repetible, para que crecer no dependa de tener suerte cada mes.",
    description:
      "Estrategia de contenido para marcas que quieren crecer sin depender de publicidad: diagnóstico de posicionamiento, definición de pilares, formatos validados con datos y un sistema de producción que tu equipo pueda mantener sin mí.",
    intro:
      "El crecimiento orgánico no se compra. Se construye una vez, se documenta y se repite. Eso es lo que entrego: el sistema, no una campaña.",
    metaTitle: "Estrategia de contenido y crecimiento orgánico en Barcelona",
    metaDescription:
      "Estrategia de contenido en Barcelona desde 990 €: pilares, formatos validados con datos y un sistema de producción que tu equipo sostiene sin mí.",
    quickAnswer:
      "Una estrategia de contenido define qué publicar, en qué formato y con qué frecuencia, a partir de datos de tu audiencia real y no de suposiciones. La entrego como un sistema documentado desde 990 €: pilares, plantillas de guion y proceso de producción que tu equipo puede sostener sin mí. Es el mismo marco con el que Reino Selva llegó a 2,6 millones de visualizaciones en un mes.",
    includes: [
      "Diagnóstico de posicionamiento: qué dices, a quién se lo dices y quién te está escuchando de verdad",
      "Pilares de contenido definidos, con el papel que cumple cada uno",
      "Formatos validados con datos, no elegidos en una reunión",
      "Plantillas de guion reutilizables para cada pilar",
      "Estructura fija de título, descripción y gancho",
      "Calendario tipo y ritmo de producción realista para tu equipo",
      "Cuadro de métricas: qué mirar, cada cuánto y qué decisión dispara cada número",
      "Sesión de traspaso grabada, para que el sistema sobreviva a un cambio de persona",
    ],
    process: [
      {
        title: "Auditoría de posicionamiento",
        detail:
          "Reviso lo que has publicado, cómo ha rendido y qué distancia hay entre la audiencia que crees tener y la que de verdad te consume. Casi ningún perfil estancado tiene un problema de volumen: tiene un problema de enfoque.",
        deliverable: "Diagnóstico escrito con la brecha identificada",
        timing: "Semana 1",
      },
      {
        title: "Definición de pilares",
        detail:
          "Tres o cuatro territorios de contenido, cada uno con un trabajo concreto: uno capta desconocidos, otro construye confianza, otro vende. Sin ese reparto, todo el contenido acaba haciendo lo mismo y ninguno lo hace bien.",
        deliverable: "Pilares con ejemplos y contraejemplos",
        timing: "Semana 2",
      },
      {
        title: "Validación con datos",
        detail:
          "Se producen piezas de prueba por pilar y se mira qué aguanta. Aquí es donde se cae la mitad de lo que parecía buena idea sobre el papel, y por eso este paso va antes de documentar nada.",
        deliverable: "Formatos ganadores por pilar",
        timing: "Semanas 3-5",
      },
      {
        title: "Documentación y traspaso",
        detail:
          "Todo lo que ha funcionado se convierte en plantillas y en proceso escrito, y te lo entrego en una sesión grabada. El objetivo no es un pico de alcance: es una base que siga creciendo cuando yo ya no lleve el día a día.",
        deliverable: "Manual de contenido y sesión de traspaso",
        timing: "Semana 6",
      },
    ],
    pricing: {
      from: 990,
      per: null,
      label: "desde 990 € el proyecto",
      includes: [
        "Las cuatro fases completas, unas seis semanas de trabajo",
        "Documentación entregada en formato editable, tuya para siempre",
        "Una revisión de seguimiento a los dos meses",
      ],
      excludes: [
        "La ejecución mensual, que es el servicio de gestión de redes sociales",
        "La producción de las piezas de prueba con equipo externo",
      ],
      note: "Es un proyecto cerrado con precio cerrado. Si después quieres que lo ejecute yo, el importe se descuenta de los tres primeros meses de gestión.",
    },
    proof: ["reino-selva", "zernio"],
    notFor: [
      "Quien quiere que alguien ejecute, no que le enseñe a ejecutar. Para eso está la gestión mensual.",
      "Quien no tiene a nadie que pueda sostener la producción después. Un sistema sin quien lo ejecute es un PDF caro.",
      "Quien necesita resultados este mes. Esto construye una base; el pico rápido lo da la gestión o la publicidad.",
    ],
    faq: [
      {
        question: "¿Qué diferencia hay entre esto y la gestión de redes sociales?",
        answer:
          "La gestión es que lo haga yo cada mes. La estrategia es que aprendáis a hacerlo vosotros. Aquí entrego el sistema documentado —pilares, plantillas, proceso y métricas— y me voy. Mucha gente contrata primero la estrategia y después decide si quiere ejecutarla internamente o pasármela.",
      },
      {
        question: "¿Cuánto cuesta una estrategia de contenido?",
        answer:
          "Desde 990 € el proyecto completo, unas seis semanas. Es precio cerrado, no por horas. Si después contratas la gestión mensual, ese importe se descuenta de los tres primeros meses.",
      },
      {
        question: "¿Sirve si mi equipo no tiene experiencia en redes?",
        answer:
          "Sí, y de hecho es para lo que está pensado. Las plantillas de guion y la estructura fija de títulos existen precisamente para que alguien sin criterio previo pueda producir con criterio. Es el mismo marco que uso en los canales de YouTube que diseño.",
      },
      {
        question: "¿Qué pasa si el formato validado deja de funcionar?",
        answer:
          "Pasa, y el sistema lo contempla. El cuadro de métricas incluye los umbrales que indican que un formato se está agotando y qué hacer entonces. Lo que se documenta no es un formato concreto, es cómo encontrar el siguiente.",
      },
      {
        question: "¿En qué sectores funciona?",
        answer:
          "He aplicado este marco en turismo, hostelería, impresión industrial y canales de YouTube de naturaleza. Los pilares cambian por completo entre uno y otro; el método de encontrarlos no cambia.",
      },
      {
        question: "¿Incluye SEO o solo redes sociales?",
        answer:
          "El sistema cubre contenido social. Si tu negocio también necesita capturar la búsqueda que ya existe, eso es SEO y es un servicio aparte, aunque los dos se diseñan mejor a la vez: las redes crean la demanda y el SEO la recoge.",
      },
    ],
    sections: [
      {
        title: "Entender por qué no está funcionando",
        body: "El punto de partida es un diagnóstico honesto: tu posicionamiento actual, tu audiencia real frente a la que asumes, y los mensajes que estás lanzando. Casi ningún perfil estancado tiene un problema de volumen. Tiene un problema de enfoque: habla a quien no le escucha, o en un formato que esa audiencia concreta no consume. Hasta que eso no está resuelto, producir más contenido solo multiplica el mismo error.",
        image: "/images/placeholders/work-03.jpg",
        imageAlt: "Diagnóstico de posicionamiento y audiencia real de una marca",
      },
      {
        title: "Un sistema que sobrevive sin mí",
        body: "Construyo un marco que tu equipo o tú podéis mantener: pilares de contenido definidos, formatos ganadores identificados con datos, plantillas de guion y un proceso de producción claro. Es el mismo tipo de sistema que diseñé para los canales de YouTube Reino Selva y RayWild, donde el guion, el título y la descripción siguen una estructura fija y replicable. El objetivo no es un pico puntual de alcance: es una base que siga creciendo cuando yo ya no lleve el día a día.",
        image: "/images/placeholders/work-04.jpg",
        imageAlt:
          "Sistema de guion, títulos y descripciones diseñado para los canales Reino Selva y RayWild",
      },
    ],
  },
  {
    slug: "seo",
    title: "SEO y posicionamiento web",
    shortTitle: "SEO",
    h1: "Consultor SEO en Barcelona",
    shortDescription:
      "Que te encuentre quien ya te está buscando. Técnica, contenido y arquitectura.",
    description:
      "SEO técnico, estrategia de palabras clave y arquitectura de contenido para que tu web gane visibilidad en Google y atraiga tráfico que se convierte en clientes, no en visitas.",
    intro:
      "Las redes sociales crean demanda. El SEO la recoge cuando ya existe. Las dos cosas juntas son lo que hace que un negocio deje de depender de la publicidad.",
    metaTitle: "Consultor SEO en Barcelona: posicionamiento web",
    metaDescription:
      "Consultor SEO en Barcelona desde 390 € al mes: auditoría técnica, Core Web Vitals, palabras clave por intención y arquitectura de contenido que convierte.",
    quickAnswer:
      "Un consultor SEO en Barcelona cuesta desde 390 € al mes e interviene en tres frentes: base técnica (velocidad, indexación, datos estructurados), palabras clave elegidas por intención de compra y no por volumen, y arquitectura de contenido de una página por intención. Los primeros movimientos se ven entre el mes tres y el seis; antes de eso, cualquiera que te prometa resultados está adivinando.",
    includes: [
      "Auditoría técnica completa: rastreo, indexación, Core Web Vitals, móvil y datos estructurados",
      "Investigación de palabras clave ordenada por intención comercial, no por volumen",
      "Arquitectura de contenido: qué página responde a qué búsqueda, sin canibalización",
      "Optimización on-page de títulos, encabezados y textos de las páginas que importan",
      "Datos estructurados en JSON-LD para resultados enriquecidos y para motores con IA",
      "SEO local si tienes local o zona de servicio: ficha de Google, coherencia de NAP y señales locales",
      "Informe mensual con posiciones, impresiones y la acción concreta del mes siguiente",
    ],
    process: [
      {
        title: "Auditoría técnica",
        detail:
          "Reviso lo que impide que Google entienda y priorice tu web: velocidad de carga, indexación, estructura de URLs, datos estructurados, versión móvil y errores de rastreo. Sin esta base, el contenido rinde por debajo de su potencial porque estás escribiendo para un buscador que no te está leyendo bien.",
        deliverable: "Auditoría con incidencias priorizadas por impacto",
        timing: "Semanas 1-2",
      },
      {
        title: "Intención antes que volumen",
        detail:
          "Identifico las búsquedas que hacen tus clientes reales, no las que tienen más volumen. Una consulta de mil búsquedas al mes que no compra vale menos que una de treinta que sí. Es la diferencia entre subir en un ranking y que suene el teléfono.",
        deliverable: "Mapa de palabras clave por intención",
        timing: "Semana 3",
      },
      {
        title: "Arquitectura y contenido",
        detail:
          "Una página, una intención, un objetivo. Se reordena lo que ya existe, se fusiona lo que compite entre sí y se escribe lo que falta. La canibalización entre páginas propias es el problema que más veces encuentro y el que menos se diagnostica.",
        deliverable: "Arquitectura nueva y páginas reescritas",
        timing: "Meses 2-3",
      },
      {
        title: "Medición y ajuste",
        detail:
          "A partir del tercer mes hay datos suficientes en Search Console para decidir con hechos. Cada informe termina en una acción concreta para el mes siguiente, no en una captura de pantalla de posiciones.",
        deliverable: "Informe mensual con la acción del mes",
        timing: "Mensual",
      },
    ],
    pricing: {
      from: 390,
      per: "mes",
      label: "desde 390 € al mes",
      includes: [
        "Auditoría técnica inicial incluida en el primer mes",
        "Trabajo continuado de contenido y arquitectura",
        "Informe mensual y una llamada de revisión",
      ],
      excludes: [
        "Compra de enlaces, que no hago",
        "Desarrollo web pesado, que se presupuesta aparte",
        "Herramientas de pago con licencia a tu nombre",
      ],
      note: "El SEO tiene un suelo de tiempo: por debajo de seis meses no se puede juzgar. Si buscas resultados en semanas, la respuesta honesta es publicidad, no SEO.",
    },
    proof: [],
    notFor: [
      "Quien necesita clientes este mes. El SEO recoge demanda a partir del mes tres o seis; para llegar antes está la publicidad.",
      "Quien quiere posiciones garantizadas. Nadie controla el algoritmo de Google, y quien te diga lo contrario te está vendiendo humo.",
      "Quien no puede tocar su web. Si el desarrollo está bloqueado por un tercero que no responde, el SEO técnico no se puede ejecutar.",
      "Quien vende algo que nadie busca. Si no hay demanda que capturar, el SEO no la crea: eso lo hace el contenido social.",
    ],
    faq: [
      {
        question: "¿Cuánto cuesta un consultor SEO en Barcelona?",
        answer:
          "Mi servicio empieza en 390 € al mes, con la auditoría técnica incluida en el primer mes. En el mercado, una consultoría SEO para un negocio local va de 400 a 1.200 € al mes, y un proyecto grande sube de ahí. Ese suelo cubre un negocio con una sola ubicación y un objetivo claro; si hay varias sedes o varios idiomas, el alcance cambia y el presupuesto también.",
      },
      {
        question: "¿Cuánto tarda el SEO en dar resultados?",
        answer:
          "Los arreglos técnicos se notan en semanas en cómo Google rastrea la web. Los movimientos de posición reales llegan entre el mes tres y el seis, y la consolidación al año. Es el plazo real del canal: cualquiera que te prometa la primera posición en un mes está adivinando o mintiendo.",
      },
      {
        question: "¿Compras enlaces?",
        answer:
          "No. Los enlaces se ganan con contenido que alguien quiera citar y con presencia real en tu sector. Comprar enlaces funciona hasta que deja de funcionar, y cuando deja de funcionar se lleva por delante todo lo demás.",
      },
      {
        question: "¿Trabajas el SEO local y Google Business Profile?",
        answer:
          "Sí, y si tienes local o zona de servicio es lo primero que trabajo, porque es donde antes se ve el retorno. Incluye la ficha de Google, la coherencia de nombre, dirección y teléfono en directorios y las señales locales en la propia web.",
      },
      {
        question: "¿Puedo contratar solo la auditoría?",
        answer:
          "Sí, como parte del servicio de auditoría y consultoría digital. Sale un diagnóstico y una lista de acciones priorizada que puede ejecutar tu equipo o cualquier otro proveedor. No hay obligación de contratar nada después.",
      },
      {
        question: "¿De quién son los accesos y los datos?",
        answer:
          "Tuyos, siempre, y por escrito antes de empezar. El dominio, el hosting, Search Console, Analytics y cualquier cuenta que se cree van a tu nombre. Si un día dejamos de trabajar juntos, no tienes que pedirme nada.",
      },
      {
        question: "¿Qué es GEO y lo trabajas?",
        answer:
          "GEO es optimizar para que te citen los buscadores con inteligencia artificial: AI Overviews de Google, ChatGPT, Perplexity. Sí lo trabajo, y se solapa mucho con el SEO clásico: respuestas autocontenidas, datos estructurados, cifras atribuibles y una entidad clara. Esta misma web está montada así.",
      },
    ],
    sections: [
      {
        title: "Base técnica sólida",
        body: "Reviso lo que impide que Google entienda y priorice tu web: velocidad de carga y Core Web Vitals, indexación, estructura de URLs, datos estructurados, versión móvil y errores de rastreo. Sin esta base, cualquier esfuerzo de contenido rinde por debajo de su potencial: estás escribiendo para un buscador que no te está leyendo bien.",
        image: "/images/placeholders/work-05.jpg",
        imageAlt: "Auditoría técnica de SEO y Core Web Vitals",
      },
      {
        title: "Palabras clave que traen clientes, no visitas",
        body: "Identifico las búsquedas que hacen tus clientes reales, no las que tienen más volumen, y diseño la arquitectura de contenido que responde a cada intención. Una página, una intención, un objetivo. Es la diferencia entre subir en un ranking y que suene el teléfono.",
        image: "/images/placeholders/work-06.jpg",
        imageAlt:
          "Estrategia de palabras clave y arquitectura de contenido orientada a conversión",
      },
    ],
  },
  {
    slug: "desarrollo-web",
    title: "Diseño y desarrollo web",
    shortTitle: "Desarrollo web",
    h1: "Diseño y desarrollo web en Barcelona",
    shortDescription:
      "Webs rápidas, indexables y construidas para que el visitante haga algo.",
    description:
      "Diseño y desarrollo de webs y landing pages rápidas, accesibles y optimizadas para buscadores, construidas desde el primer día alrededor de una acción concreta: que el visitante contacte, reserve o compre.",
    intro:
      "Una web bonita que no convierte es un gasto con buen aspecto. Cada página empieza por una pregunta: qué queremos que haga quien llega aquí.",
    metaTitle: "Diseño y desarrollo web en Barcelona",
    metaDescription:
      "Diseño y desarrollo web en Barcelona desde 1.190 €: sitios rápidos, accesibles y optimizados para SEO desde el primer día, pensados para convertir visitas en clientes.",
    quickAnswer:
      "Una web profesional en Barcelona cuesta desde 1.190 € y debería incluir siempre cuatro cosas: rendimiento medido en móvil, SEO técnico de base, textos escritos para convertir y la propiedad del código y del dominio a tu nombre. Si un presupuesto no menciona las cuatro, lo que estás comprando es una plantilla con tu logo encima.",
    includes: [
      "Diseño a medida, sin plantilla comprada",
      "Desarrollo con tecnologías modernas orientadas a velocidad en móvil",
      "SEO técnico de base: estructura de encabezados, metadatos, datos estructurados y sitemap",
      "Textos escritos para la web y para la búsqueda, no rellenados",
      "Accesibilidad integrada en cada componente, no añadida al final",
      "Formulario de contacto conectado y probado, con aviso legal y consentimiento correctos",
      "Analítica configurada y comprobada antes de entregar",
      "Propiedad total del dominio, el hosting y el código, a tu nombre y por escrito",
    ],
    process: [
      {
        title: "Definir la acción",
        detail:
          "Cada página empieza por una pregunta: qué queremos que haga quien llega aquí. Contactar, reservar, comprar o llamar. Todo lo demás —estructura, textos, botones— se ordena detrás de esa respuesta. Una web sin esa decisión tomada acaba siendo un folleto.",
        deliverable: "Mapa de páginas con su objetivo",
        timing: "Semana 1",
      },
      {
        title: "Estructura y textos",
        detail:
          "Escribo los textos antes de diseñar, porque el diseño tiene que servir al mensaje y no al revés. En paralelo se define la arquitectura de URLs para que cada página responda a una intención de búsqueda distinta desde el día uno.",
        deliverable: "Textos aprobados y arquitectura de URLs",
        timing: "Semanas 2-3",
      },
      {
        title: "Diseño y desarrollo",
        detail:
          "Desarrollo priorizando la velocidad de carga en móvil, porque afecta directamente al posicionamiento y a la conversión. Una web que carga un segundo más tarde no es una web peor: es una web con menos clientes.",
        deliverable: "Web en entorno de pruebas, revisable",
        timing: "Semanas 4-7",
      },
      {
        title: "Medición y entrega",
        detail:
          "Antes de publicar se comprueba rendimiento real en móvil, indexación, formularios y analítica. Se entrega con todos los accesos a tu nombre y una sesión para que sepas mantenerla.",
        deliverable: "Web publicada, medida y traspasada",
        timing: "Semana 8",
      },
    ],
    pricing: {
      from: 1190,
      per: null,
      label: "desde 1.190 € el proyecto",
      includes: [
        "Web de hasta seis páginas, diseño a medida y textos escritos",
        "SEO técnico de base y analítica configurada",
        "Un mes de ajustes después de publicar",
      ],
      excludes: [
        "El dominio y el hosting, que se contratan a tu nombre",
        "Tienda online y pasarela de pago, que se presupuestan aparte",
        "Fotografía y vídeo de producción",
      ],
      note: "Una landing page suelta parte de 450 €. El precio depende del número de páginas y de si hay que escribir los textos desde cero.",
    },
    proof: [],
    notFor: [
      "Quien busca la web más barata posible. Por debajo de cierto punto lo que se compra es una plantilla, y sale más caro rehacerla que hacerla bien.",
      "Quien necesita una tienda online grande con miles de referencias. Eso es otro tipo de proyecto y otro tipo de proveedor.",
      "Quien quiere entregar el contenido más adelante. Sin textos no hay web: es la parte que más se retrasa y la que más decide el resultado.",
    ],
    faq: [
      {
        question: "¿Cuánto cuesta una página web en Barcelona?",
        answer:
          "Desde 1.190 € una web corporativa de hasta seis páginas con diseño a medida, textos escritos y SEO técnico de base. Una landing page suelta parte de 450 €. Lo que mueve el precio no son las páginas, son los textos: escribirlos desde cero es la mitad del trabajo.",
        },
      {
        question: "¿Cuánto se tarda?",
        answer:
          "Unas ocho semanas para una web corporativa, contando revisiones. El plazo lo suele marcar el cliente, no el desarrollo: la fase que más se alarga es siempre la aprobación de textos y la recopilación de fotos.",
      },
      {
        question: "¿La web es mía?",
        answer:
          "Sí, entera, y por escrito antes de empezar: dominio, hosting, código y accesos analíticos a tu nombre. Si mañana quieres llevártela a otro proveedor, puedes hacerlo sin pedirme permiso. Que esto no esté claro es la trampa más común del sector.",
      },
      {
        question: "¿Con qué tecnología trabajas?",
        answer:
          "Next.js y React para proyectos a medida, que es lo que da mejor rendimiento en móvil y mejor base técnica de SEO. Si tu equipo necesita editar contenido a diario, monto un gestor encima. Esta misma web está hecha así.",
      },
      {
        question: "¿Incluye el mantenimiento?",
        answer:
          "El primer mes de ajustes va incluido. Después puedes contratar mantenimiento aparte o llevarlo tú: te dejo la web documentada para que sea posible lo segundo.",
      },
      {
        question: "¿Haces tiendas online?",
        answer:
          "Tiendas pequeñas, de catálogo reducido, sí. Para un ecommerce grande con miles de referencias, gestión de stock e integraciones de logística, necesitas un proveedor especializado en eso y te lo diré en la primera llamada.",
      },
    ],
    sections: [
      {
        title: "Rendimiento y accesibilidad de serie",
        body: "Desarrollo con tecnologías modernas que priorizan la velocidad de carga y el rendimiento en móvil, porque afectan directamente al posicionamiento y a la tasa de conversión. La accesibilidad no es un extra que se añade al final: forma parte de cómo se construye cada componente. Una web que carga un segundo más tarde no es una web peor: es una web con menos clientes.",
        image: "/images/placeholders/work-01.jpg",
        imageAlt: "Desarrollo web optimizado para velocidad de carga y accesibilidad",
      },
      {
        title: "Construida para convertir",
        body: "La estructura, los textos y las llamadas a la acción se ordenan según lo que queremos que pase en esa página, y se miden después con datos reales de uso para poder ajustarlos. El diseño no es una cuestión de gusto: es una cuestión de dónde mira la gente y qué hace a continuación.",
        image: "/images/placeholders/work-02.jpg",
        imageAlt: "Estructura de una landing page orientada a conversión",
      },
    ],
  },
  {
    slug: "publicidad-meta-ads-google-ads",
    title: "Publicidad en Meta Ads y Google Ads",
    shortTitle: "Publicidad online",
    h1: "Gestión de Meta Ads y Google Ads en Barcelona",
    shortDescription:
      "Campañas donde el creativo manda y la cuenta se mide por clientes, no por clics.",
    description:
      "Gestión de campañas de publicidad en Instagram, Facebook y Google para negocios que ya tienen algo que funciona y quieren acelerarlo, con el creativo producido en la misma casa que la estrategia.",
    intro:
      "La publicidad no arregla una oferta que no interesa a nadie: la hace fracasar más rápido y con factura. Cuando sí hay demanda, es el acelerador más directo que existe.",
    metaTitle: "Meta Ads y Google Ads en Barcelona",
    metaDescription:
      "Gestión de Meta Ads y Google Ads en Barcelona desde 350 € al mes más inversión. El creativo se produce aquí, que es lo que decide el 80 % del resultado.",
    quickAnswer:
      "La gestión de campañas de Meta Ads o Google Ads en Barcelona cuesta desde 350 € al mes más la inversión publicitaria, que va directa a la plataforma y a tu nombre. En Meta, el anuncio decide más que la segmentación: por eso produzco el creativo y la campaña en el mismo sitio. En Google recoges demanda que ya existe; en Meta la creas.",
    includes: [
      "Estructura de cuenta y de campañas desde cero, o auditoría de la existente",
      "Producción del creativo: guion, grabación y edición de los anuncios en vídeo",
      "Redacción de textos y titulares, con varias variantes para poder comparar",
      "Configuración de seguimiento de conversiones y comprobación de que mide de verdad",
      "Gestión y optimización continua del presupuesto entre campañas",
      "Informe mensual con coste por resultado y decisión para el mes siguiente",
      "Coordinación con el contenido orgánico, para que lo que funciona sin pagar se amplifique",
    ],
    process: [
      {
        title: "Comprobar que toca invertir",
        detail:
          "Antes de configurar nada miro si hay demanda que capturar y si la web convierte. Meter presupuesto en una página que no convierte es la forma más cara de descubrir que la página no convierte, y es la conversación que más veces he tenido.",
        deliverable: "Diagnóstico de si invertir ahora o todavía no",
        timing: "Semana 1",
      },
      {
        title: "Medición primero",
        detail:
          "Se configuran las conversiones y se comprueba que registran de verdad, con una compra o un formulario real. Una cuenta que optimiza sobre datos mal medidos aprende exactamente lo que no debe.",
        deliverable: "Seguimiento de conversiones verificado",
        timing: "Semana 1",
      },
      {
        title: "Creativo y lanzamiento",
        detail:
          "En Meta el creativo pesa más que el público: la plataforma encuentra a la gente si el anuncio la para. Se producen varias piezas con ganchos distintos y se lanzan contra estructuras simples, sin trocear el presupuesto en veinte conjuntos que nunca salen del aprendizaje.",
        deliverable: "Campañas activas con varias variantes de creativo",
        timing: "Semanas 2-3",
      },
      {
        title: "Optimizar y escalar",
        detail:
          "Se corta lo que no rinde, se concentra el presupuesto en lo que sí y se renueva el creativo antes de que se sature, que en vídeo vertical ocurre rápido. El informe habla de coste por cliente, no de impresiones.",
        deliverable: "Informe mensual por coste de resultado",
        timing: "Mensual",
      },
    ],
    pricing: {
      from: 350,
      per: "mes",
      label: "desde 350 € al mes, más inversión",
      includes: [
        "Gestión de una plataforma, Meta o Google",
        "Producción de hasta tres creativos en vídeo al mes",
        "Seguimiento de conversiones e informe mensual",
      ],
      excludes: [
        "La inversión publicitaria, que va directa a la plataforma con tu tarjeta",
        "La segunda plataforma, que se suma aparte",
      ],
      note: "La cuenta publicitaria se crea siempre a tu nombre. Si dejamos de trabajar juntos, el histórico de aprendizaje se queda contigo, que es donde está el valor acumulado.",
    },
    proof: [],
    notFor: [
      "Quien tiene menos de 300 € al mes de inversión. Por debajo de ahí la plataforma no sale de la fase de aprendizaje y el dinero se quema sin enseñar nada.",
      "Quien no tiene la web o el proceso de venta resuelto. La publicidad amplifica lo que ya pasa, incluido lo malo.",
      "Quien quiere resultados sin ceder material para producir anuncios. Sin creativo propio solo queda competir a precio.",
    ],
    faq: [
      {
        question: "¿Cuánto cuesta gestionar campañas de Meta Ads o Google Ads?",
        answer:
          "Desde 350 € al mes de gestión, más la inversión publicitaria, que va directa a la plataforma con tu tarjeta y a tu nombre. Nunca cobro un porcentaje de la inversión: ese modelo premia gastar más, no vender más.",
      },
      {
        question: "¿Cuánta inversión mínima necesito?",
        answer:
          "Unos 300 € al mes es el suelo real para que una campaña salga de la fase de aprendizaje y produzca datos útiles. Por debajo de eso el algoritmo no tiene suficientes conversiones para optimizar y el presupuesto se gasta sin enseñar nada.",
      },
      {
        question: "¿Google Ads o Meta Ads, qué me conviene?",
        answer:
          "Google recoge demanda que ya existe: alguien busca lo que vendes y tú apareces. Meta la crea: nadie estaba buscándote y tu anuncio le interesa igual. Si tu servicio se busca por su nombre, empieza por Google. Si tienes que explicar por qué le interesa a alguien, empieza por Meta.",
      },
      {
        question: "¿Por qué dices que el creativo importa más que la segmentación?",
        answer:
          "Porque las plataformas de Meta llevan años siendo mejores que cualquier humano encontrando al público adecuado, siempre que el anuncio le pare el dedo. Puedes segmentar de forma impecable y no vender nada con un mal creativo; con un buen creativo y una segmentación amplia, sí vendes.",
      },
      {
        question: "¿De quién es la cuenta publicitaria?",
        answer:
          "Tuya, creada a tu nombre desde el principio. El histórico de una cuenta es aprendizaje acumulado que vale dinero, y he visto a demasiada gente empezar de cero porque su agencia lo tenía todo en una cuenta propia.",
      },
      {
        question: "¿En cuánto tiempo se ven resultados?",
        answer:
          "Las primeras conversiones pueden llegar en días, pero la lectura fiable es a partir de las cuatro o seis semanas: antes de eso la campaña sigue aprendiendo y cualquier conclusión es ruido. Lo que sí se ve enseguida es si el creativo para el dedo o no.",
      },
    ],
    sections: [
      {
        title: "El creativo decide, la segmentación acompaña",
        body: "En Meta Ads la plataforma es mucho mejor que cualquier persona encontrando al público adecuado, siempre que el anuncio consiga pararlo. Por eso el trabajo se concentra donde de verdad cambia el resultado: guion, gancho y montaje de la pieza. Produzco los anuncios en el mismo sitio donde diseño la estrategia, así que el creativo que funciona en orgánico se convierte en anuncio sin pasar por tres proveedores.",
        image: "/images/placeholders/work-05.jpg",
        imageAlt: "Producción de creativos en vídeo para campañas de Meta Ads",
      },
      {
        title: "Medir clientes, no impresiones",
        body: "Antes de gastar un euro se configura el seguimiento de conversiones y se comprueba con una conversión real que registra bien. A partir de ahí, cada informe habla de cuánto cuesta conseguir un cliente y qué se hace el mes que viene, no de cuántas personas vieron el anuncio. El objetivo de una cuenta publicitaria no es alcance: es margen.",
        image: "/images/placeholders/work-06.jpg",
        imageAlt: "Informe de coste por conversión de una campaña de Google Ads",
      },
    ],
  },
  {
    slug: "auditoria-consultoria-digital",
    title: "Auditoría y consultoría digital",
    shortTitle: "Consultoría",
    h1: "Auditoría y consultoría de marketing digital en Barcelona",
    shortDescription:
      "Un diagnóstico completo y una lista de acciones ordenada por impacto. Sin informe de 100 páginas.",
    description:
      "Auditoría de tu presencia digital completa (redes sociales, web y SEO) con un plan de acción priorizado por impacto y esfuerzo, listo para que lo ejecute tu equipo o para que lo ejecute yo.",
    intro:
      "A veces no necesitas externalizar la gestión. Necesitas saber exactamente qué hacer y en qué orden. Eso es lo que entrega una auditoría.",
    metaTitle: "Auditoría de marketing digital en Barcelona",
    metaDescription:
      "Auditoría de marketing digital en Barcelona desde 290 €: diagnóstico de redes, web y SEO con un plan de acción priorizado por impacto y esfuerzo. Sin permanencia.",
    quickAnswer:
      "Una auditoría de marketing digital revisa redes sociales, web, SEO y la coherencia del mensaje entre canales, y termina en una lista de acciones ordenada por impacto y esfuerzo. Cuesta desde 290 € y se entrega en dos semanas. El entregable no es un PDF de cien páginas: es qué hacer esta semana, qué puede esperar y qué no merece la pena hacer nunca.",
    includes: [
      "Análisis de los perfiles sociales: formatos, retención, frecuencia y audiencia real",
      "Auditoría técnica de la web: velocidad, indexación, móvil y datos estructurados",
      "Revisión SEO: palabras clave, canibalización entre páginas y competencia real",
      "Revisión de la coherencia del mensaje entre web, redes y ficha de Google",
      "Análisis de tres competidores directos, con lo que hacen mejor que tú",
      "Lista de acciones priorizada por impacto y esfuerzo, con responsable sugerido",
      "Una sesión de una hora para revisarlo y resolver dudas, grabada",
    ],
    process: [
      {
        title: "Recogida de accesos",
        detail:
          "Necesito ver los datos, no las impresiones: métricas de los perfiles, Search Console si existe y analítica de la web. Media hora tuya y el resto lo hago yo.",
        deliverable: "Alcance cerrado y accesos verificados",
        timing: "Día 1",
      },
      {
        title: "Análisis del conjunto",
        detail:
          "Analizo tu presencia digital como un sistema: perfiles, web, buscadores y coherencia del mensaje. Los problemas de una marca rara vez están aislados en un canal, y tratarlos por separado suele ser la razón exacta por la que llevan años sin resolverse.",
        deliverable: "Diagnóstico por canal y del conjunto",
        timing: "Semana 1",
      },
      {
        title: "Priorización",
        detail:
          "Cada hallazgo se ordena por impacto y por esfuerzo. Lo que da mucho y cuesta poco va arriba; lo que da poco y cuesta mucho se descarta explícitamente, porque decidir qué no hacer ahorra más dinero que casi cualquier acción.",
        deliverable: "Plan de acción priorizado",
        timing: "Semana 2",
      },
      {
        title: "Sesión de entrega",
        detail:
          "Una hora para repasar el plan y responder a todo. Queda grabada para que la pueda ver quien vaya a ejecutar. No hay obligación de contratar nada después: el plan es tuyo y lo puede ejecutar cualquiera.",
        deliverable: "Sesión grabada y plan entregado",
        timing: "Semana 2",
      },
    ],
    pricing: {
      from: 290,
      per: null,
      label: "desde 290 €",
      includes: [
        "Auditoría de redes, web y SEO, y análisis de tres competidores",
        "Plan de acción priorizado por impacto y esfuerzo",
        "Sesión de entrega de una hora, grabada",
      ],
      excludes: [
        "La ejecución del plan, que puedes hacer tú, tu equipo o yo",
        "Auditoría de cuentas publicitarias con inversión alta, que se presupuesta aparte",
      ],
      note: "Si después decides que ejecute yo el plan, el importe de la auditoría se descuenta del primer mes.",
    },
    proof: [],
    notFor: [
      "Quien ya sabe qué hacer y solo necesita manos. Eso es ejecución, y sale más a cuenta contratarla directamente.",
      "Quien quiere un informe para justificar una decisión ya tomada. Si el diagnóstico va a contradecir el plan, prefiero no hacerlo.",
      "Quien no va a ejecutar nada después. Una auditoría sin ejecución es un gasto, no una inversión, y te lo diré antes de cobrarla.",
    ],
    faq: [
      {
        question: "¿Cuánto cuesta una auditoría de marketing digital?",
        answer:
          "Desde 290 €, con entrega en dos semanas y sesión de repaso incluida. Si después contratas cualquiera de mis servicios, ese importe se descuenta del primer mes, así que en la práctica la auditoría sale gratis si acabamos trabajando juntos.",
      },
      {
        question: "¿Qué recibo exactamente?",
        answer:
          "Un documento con el diagnóstico por canal y una lista de acciones ordenada por impacto y esfuerzo, con qué hacer esta semana, qué puede esperar y qué no merece la pena hacer nunca. Más una sesión de una hora grabada. No recibes un PDF de cien páginas que nadie abre.",
      },
      {
        question: "¿Tengo que contratarte después?",
        answer:
          "No, y está pensado para que no haga falta. El plan está escrito para que lo ejecute tu equipo o cualquier otro proveedor. Si la auditoría solo sirviera contratándome a mí, no sería una auditoría, sería una propuesta comercial disfrazada.",
      },
      {
        question: "¿Auditas también cuentas de publicidad?",
        answer:
          "Sí, la estructura de cuenta, el seguimiento de conversiones y el coste por resultado entran en el alcance estándar. Si hay una inversión alta y varios mercados, eso se presupuesta aparte porque es un trabajo bastante mayor.",
      },
      {
        question: "¿Cuánto tarda?",
        answer:
          "Dos semanas desde que tengo los accesos. La parte que lo puede retrasar es conseguir los permisos de analítica, así que conviene pedirlos el primer día.",
      },
      {
        question: "¿Sirve si mi negocio es pequeño?",
        answer:
          "Sí, y suele ser donde más rinde, porque en un negocio pequeño casi siempre hay dos o tres cosas mal resueltas que están frenando todo lo demás. En una estructura grande el diagnóstico es más largo y las acciones tardan más en poder ejecutarse.",
      },
    ],
    sections: [
      {
        title: "Diagnóstico completo, sin puntos ciegos",
        body: "Analizo tu presencia digital como un conjunto: perfiles sociales, web, posicionamiento en buscadores y la coherencia del mensaje entre todos ellos. Los problemas de una marca rara vez están aislados en un solo canal, y tratarlos por separado suele ser exactamente la razón por la que llevan años sin resolverse.",
        image: "/images/placeholders/work-03.jpg",
        imageAlt: "Auditoría completa de presencia digital: redes sociales, web y SEO",
      },
      {
        title: "Una lista priorizada, no un informe",
        body: "El resultado no es un PDF de cien páginas que nadie abre. Es una lista concreta de acciones ordenadas por impacto y esfuerzo: qué hacer esta semana, qué puede esperar y qué no merece la pena hacer nunca. Si quieres, después acompaño la implementación; si no, te queda un plan que puede ejecutar cualquiera.",
        image: "/images/placeholders/work-04.jpg",
        imageAlt:
          "Plan de acción de marketing digital priorizado por impacto y esfuerzo",
      },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((service) => service.slug === slug);
}

/** Una entrada del desplegable de servicios del formulario de contacto. */
export type ServiceOption = {
  value: string;
  label: string;
  /** Versión corta, para el asunto del email de aviso. */
  shortLabel: string;
};

/**
 * Valor de escape del desplegable. No es un servicio y nunca tendrá página:
 * está para que quien no sepa todavía qué necesita pueda enviar el formulario
 * en lugar de elegir algo al azar y ensuciar el dato.
 */
export const SERVICE_OPTION_UNDECIDED = "no-lo-se";

/**
 * Las opciones del desplegable, derivadas de `SERVICES` para que añadir un
 * servicio no obligue a acordarse de este fichero.
 *
 * Se llama desde el Server Component de `/contacto` y el resultado viaja al
 * formulario como prop: importar `SERVICES` desde un componente `"use client"`
 * arrastraría al bundle toda la prosa de este fichero —fichas, FAQs, precios—
 * para usar seis títulos.
 */
export function contactServiceOptions(): ServiceOption[] {
  return [
    ...SERVICES.map((service) => ({
      value: service.slug,
      label: service.title,
      shortLabel: service.shortTitle,
    })),
    {
      value: SERVICE_OPTION_UNDECIDED,
      label: "Todavía no lo sé / Otro",
      shortLabel: "Sin definir",
    },
  ];
}
